name: GitHub Actions Test
# run-name: ${{ github.actor }} workflow test
on: [push]
jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi! I'm running because of a ${{ github.event_name }} event."
      - run: echo "Checking out the repository from ${{ github.repository }}."
      - name: Clone repository code
        uses: actions/checkout@v4
      - run: echo "Repository cloned, I think I'm ready. The files look like this:"
      - name: List files
        run: |
          ls ${{ github.workspace}}
      - name: login to Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Test Azure login for getting details
        run: az account show
      - name: install azure ML cli extention
        run: az extension  add -n azure-cli-ml

      - name: Create and run Azure ML job
        run: az ml job create --file job.yaml --resource-group Test1 --workspace-name test1

